spring:
  application:
    name: analyzer
  config:
    import: "optional:configserver:"
  cloud:
    config:
      fail-fast: false
      retry:
        useRandomPolicy: true
        max-interval: 6000
      discovery:
        enabled: true
        serviceId: config-server

server:
  port: 59091

eureka:
  instance:
    preferIpAddress: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/